{"text": "2023-01-31 06:16:00.910 | DEBUG    | dodo:<module>:31 - debug-level log\n", "record": {"elapsed": {"repr": "0:00:00.340931", "seconds": 0.340931}, "exception": null, "extra": {"data": {"key1": 123}}, "file": {"name": "dodo.py", "path": "/Users/kyleking/Developer/packages/tail-jsonl/dodo.py"}, "function": "<module>", "level": {"icon": "🐞", "name": "DEBUG", "no": 10}, "line": 31, "message": "debug-level log", "module": "dodo", "name": "dodo", "process": {"id": 16268, "name": "MainProcess"}, "thread": {"id": 8821244160, "name": "MainThread"}, "time": {"repr": "2023-01-31 06:16:00.910671-05:00", "timestamp": 1675160160.910671}}}
{"text": "2023-01-31 06:16:00.910 | INFO     | dodo:<module>:32 - info-level log\n", "record": {"elapsed": {"repr": "0:00:00.341175", "seconds": 0.341175}, "exception": null, "extra": {}, "file": {"name": "dodo.py", "path": "/Users/kyleking/Developer/packages/tail-jsonl/dodo.py"}, "function": "<module>", "level": {"icon": "ℹ️", "name": "INFO", "no": 20}, "line": 32, "message": "info-level log", "module": "dodo", "name": "dodo", "process": {"id": 16268, "name": "MainProcess"}, "thread": {"id": 8821244160, "name": "MainThread"}, "time": {"repr": "2023-01-31 06:16:00.910915-05:00", "timestamp": 1675160160.910915}}}
{"text": "2023-01-31 06:16:00.911 | WARNING  | dodo:<module>:33 - warning-level log\n", "record": {"elapsed": {"repr": "0:00:00.341294", "seconds": 0.341294}, "exception": null, "extra": {}, "file": {"name": "dodo.py", "path": "/Users/kyleking/Developer/packages/tail-jsonl/dodo.py"}, "function": "<module>", "level": {"icon": "⚠️", "name": "WARNING", "no": 30}, "line": 33, "message": "warning-level log", "module": "dodo", "name": "dodo", "process": {"id": 16268, "name": "MainProcess"}, "thread": {"id": 8821244160, "name": "MainThread"}, "time": {"repr": "2023-01-31 06:16:00.911034-05:00", "timestamp": 1675160160.911034}}}
{"text": "2023-01-31 06:16:00.911 | ERROR    | dodo:<module>:34 - error-level log\n", "record": {"elapsed": {"repr": "0:00:00.341591", "seconds": 0.341591}, "exception": null, "extra": {}, "file": {"name": "dodo.py", "path": "/Users/kyleking/Developer/packages/tail-jsonl/dodo.py"}, "function": "<module>", "level": {"icon": "❌", "name": "ERROR", "no": 40}, "line": 34, "message": "error-level log", "module": "dodo", "name": "dodo", "process": {"id": 16268, "name": "MainProcess"}, "thread": {"id": 8821244160, "name": "MainThread"}, "time": {"repr": "2023-01-31 06:16:00.911331-05:00", "timestamp": 1675160160.911331}}}
{"text": "2023-01-31 06:16:00.911 | ERROR    | dodo:<module>:38 - exception-level log\nTraceback (most recent call last):\n\n  File \"/Users/kyleking/Developer/packages/tail-jsonl/.venv/bin/doit\", line 8, in <module>\n    sys.exit(main())\n    │   │    └ <function main at 0x103c3a2a0>\n    │   └ <built-in function exit>\n    └ <module 'sys' (built-in)>\n  File \"/Users/kyleking/Developer/packages/tail-jsonl/.venv/lib/python3.11/site-packages/doit/__main__.py\", line 8, in main\n    sys.exit(DoitMain().run(sys.argv[1:]))\n    │   │    │              │   └ ['/Users/kyleking/Developer/packages/tail-jsonl/.venv/bin/doit', 'run', 'test']\n    │   │    │              └ <module 'sys' (built-in)>\n    │   │    └ <class 'doit.doit_cmd.DoitMain'>\n    │   └ <built-in function exit>\n    └ <module 'sys' (built-in)>\n  File \"/Users/kyleking/Developer/packages/tail-jsonl/.venv/lib/python3.11/site-packages/doit/doit_cmd.py\", line 294, in run\n    return command.parse_execute(args)\n           │       │             └ ['test']\n           │       └ <function Command.parse_execute at 0x1037e0fe0>\n           └ <doit.cmd_run.Run object at 0x103876f50>\n  File \"/Users/kyleking/Developer/packages/tail-jsonl/.venv/lib/python3.11/site-packages/doit/cmd_base.py\", line 150, in parse_execute\n    return self.execute(params, args)\n           │    │       │       └ ['test']\n           │    │       └ {'dep_file': '.doit.db', 'backend': 'dbm', 'codec_cls': 'json', 'check_file_uptodate': 'md5', 'dodoFile': 'dodo.py', 'cwdPath...\n           │    └ <function DoitCmdBase.execute at 0x1037e1da0>\n           └ <doit.cmd_run.Run object at 0x103876f50>\n  File \"/Users/kyleking/Developer/packages/tail-jsonl/.venv/lib/python3.11/site-packages/doit/cmd_base.py\", line 524, in execute\n    self.loader.setup(params)\n    │    │      │     └ {'dep_file': '.doit.db', 'backend': 'dbm', 'codec_cls': 'json', 'check_file_uptodate': 'md5', 'dodoFile': 'dodo.py', 'cwdPath...\n    │    │      └ <function DodoTaskLoader.setup at 0x1037e1800>\n    │    └ <doit.cmd_base.DodoTaskLoader object at 0x102f748d0>\n    └ <doit.cmd_run.Run object at 0x103876f50>\n  File \"/Users/kyleking/Developer/packages/tail-jsonl/.venv/lib/python3.11/site-packages/doit/cmd_base.py\", line 394, in setup\n    self.namespace = dict(inspect.getmembers(loader.get_module(\n    │    │                │       │          │      └ <function get_module at 0x102f6fce0>\n    │    │                │       │          └ <module 'doit.loader' from '/Users/kyleking/Developer/packages/tail-jsonl/.venv/lib/python3.11/site-packages/doit/loader.py'>\n    │    │                │       └ <function getmembers at 0x102f1dbc0>\n    │    │                └ <module 'inspect' from '/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/insp...\n    │    └ None\n    └ <doit.cmd_base.DodoTaskLoader object at 0x102f748d0>\n  File \"/Users/kyleking/Developer/packages/tail-jsonl/.venv/lib/python3.11/site-packages/doit/loader.py\", line 96, in get_module\n    return importlib.import_module(os.path.splitext(file_name)[0])\n           │         │             │  │    │        └ 'dodo.py'\n           │         │             │  │    └ <function splitext at 0x102d0cea0>\n           │         │             │  └ <module 'posixpath' (frozen)>\n           │         │             └ <module 'os' (frozen)>\n           │         └ <function import_module at 0x102f1cc20>\n           └ <module 'importlib' from '/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/im...\n\n  File \"/opt/homebrew/Cellar/python@3.11/3.11.1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py\", line 126, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n           │          │           │    │        │        └ 0\n           │          │           │    │        └ None\n           │          │           │    └ 0\n           │          │           └ 'dodo'\n           │          └ <function _gcd_import at 0x102c53d80>\n           └ <module '_frozen_importlib' (frozen)>\n\n  File \"<frozen importlib._bootstrap>\", line 1206, in _gcd_import\n  File \"<frozen importlib._bootstrap>\", line 1178, in _find_and_load\n  File \"<frozen importlib._bootstrap>\", line 1149, in _find_and_load_unlocked\n  File \"<frozen importlib._bootstrap>\", line 690, in _load_unlocked\n  File \"<frozen importlib._bootstrap_external>\", line 940, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 241, in _call_with_frames_removed\n\n> File \"/Users/kyleking/Developer/packages/tail-jsonl/dodo.py\", line 36, in <module>\n    1 // 0\n\nZeroDivisionError: integer division or modulo by zero\n", "record": {"elapsed": {"repr": "0:00:00.341759", "seconds": 0.341759}, "exception": {"type": "ZeroDivisionError", "value": "integer division or modulo by zero", "traceback": true}, "extra": {}, "file": {"name": "dodo.py", "path": "/Users/kyleking/Developer/packages/tail-jsonl/dodo.py"}, "function": "<module>", "level": {"icon": "❌", "name": "ERROR", "no": 40}, "line": 38, "message": "exception-level log", "module": "dodo", "name": "dodo", "process": {"id": 16268, "name": "MainProcess"}, "thread": {"id": 8821244160, "name": "MainThread"}, "time": {"repr": "2023-01-31 06:16:00.911499-05:00", "timestamp": 1675160160.911499}}}
{"timestamp":"2025-09-10T15:31:37.651Z","level":"error","category":["app"],"message":["Failed to load comments"],"host":"localhost:8080","method":"GET","path":"/partials/comments","referer":"http://localhost:8080/comments","requestId":"4c58cd34-f521-4af1-8c6d-e61914216710","url":"http://localhost:8080/partials/comments","error":{"name":"SourceError","message":"Invalid for loop","stack":"SourceError: Invalid for loop\n    at forTag (https://deno.land/x/vento@v2.0.1/plugins/for.ts:74:11)\n    at Environment.compileTokens (https://deno.land/x/vento@v2.0.1/core/environment.ts:291:31)\n    at Environment.compile (https://deno.land/x/vento@v2.0.1/core/environment.ts:136:19)\n    at https://deno.land/x/vento@v2.0.1/core/environment.ts:250:21\n    at eventLoopTick (ext:core/01_core.js:179:7)\n    at async Environment.load (https://deno.land/x/vento@v2.0.1/core/environment.ts:255:12)\n    at async renderTemplate (file:///Users/kyleking/Developer/kyleking/app-template/src/templates/engine.ts:8:20)\n    at async file:///Users/kyleking/Developer/kyleking/app-template/src/partials/commentsRouter.ts:12:18\n    at async dispatch (file:///Users/kyleking/Developer/kyleking/app-template/node_modules/.deno/hono@4.9.6/node_modules/hono/dist/compose.js:22:17)\n    at async file:///Users/kyleking/Developer/kyleking/app-template/src/app.ts:55:7"},"request":{"method":"GET","path":"/partials/comments"}}
